### ISSUE TITLE
Contributing to Laravel To Do App

### ISSUE THREAD

**Issue by kenmush** [Dickens-odera/Laravel-To-Do-App#4]
Hello @Dickens-odera, I wanted to contribute to the current Laravel To DO app. Can you grant me the right to push to the repository?

I have attached my current implementation of tests that I think will be beneficial to future Laravel users who will be visiting this repository
[Download the  Tests by Clicking this link](https://github.com/Dickens-odera/Laravel-To-Do-App/files/4743440/odera-tests.zip)
And kudos for the good work with this repo.

The tests are under the tests/Unit and tests/Controllers folder.

Thank you and cheers

**Comment by Dickens-odera** [comment]
Hello Ken, thanks for this, yeah sure you can have a look at it. Either folk and add the changes via a pull request or make a clone and make changes on a separate branch,
